---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_terminal: false
configure_osx: false

configure_dock: true
dockitems_remove:
  - Launchpad
  - TV
  - Music
  - Keynote
  - Numbers
  - Pages
  - App Store
  - Safari
  - Freeform

mas_installed_apps:
  - { id: 1475387142, name: "Tailscale" }
  - { id: 1352778147, name: "Bitwarden" }
  - { id: 310633997, name: "WhatsApp Messenger" }

homebrew_installed_packages:
  - htop
  - bash-completion
  - gh
  - glab
  - sops
  - hugo
  - helm
  - opentofu
  - terraform
  - terragrunt
  - gnupg
  - picocom
  - go
  - node
  - jq
  - git
  - git-lfs
  - nmap
  - openssl
  - wget
  - curl
  - whois
  - neovim
  - tmux
  - neofetch
  - e2fsprogs
  - tree
  - ripgrep
  - k9s
  - kubernetes-cli
  - kind
  - pinentry
  - pinentry-mac
  - speedtest-cli
  - watch
  - telnet
  - fzf
  - docker
  - colima
  - direnv
  # ruby stuff
  - ruby
  - rbenv

homebrew_taps: []
  # - homebrew/core
  # - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - virtualbox@beta
  - git-credential-manager
  - easy-move-plus-resize
  - karabiner-elements
  - logi-options-plus
  - rectangle
  - obs
  - firefox
  - chromium
  - alacritty
  - element
  - spotify
  - slack
  - signal
  - joplin
  - chatbox
  - rocket-chat
  - discord
  - keycastr
  - netnewswire

npm_packages: []

pip_packages: []

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
