---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_terminal: false
configure_osx: false

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

homebrew_installed_packages:
  - sops
  - hugo
  - helm
  - terraform
  - terragrunt
  - gnupg
  - bitwarden-cli
  - picocom
  - go
  - node
  - syncthing
  - jq
  - git
  - nmap
  - openssl
  - wget
  - curl
  - whois
  - neovim
  - tmux
  - neofetch
  - e2fsprogs
  - tree
  - syncthing
  - bash
  - ripgrep
  - k9s
  - pinentry
  - openconnect
  - speedtest-cli
  - watch
  - bash-completion@2
  - telnet
  - qmk
  - fzf
  # LSP
  - terraform-ls
  - gopls
  - tflint
  - yarn

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - qmk/qmk

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - android-platform-tools
  - firefox
  - brave-browser
  - insomnia
  - visual-studio-code
  - iterm2
  - alacritty
  - google-cloud-sdk
  - telegram
  - element
  - slack
  - vagrant
  - docker
  - spotify
  - signal
  - joplin

npm_packages:
  - name: bash-language-server
  - name: dockerfile-language-server-nodejs

pip_packages:
  - name: jedi-language-server
  - name: python-language-server
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks:
  - tasks/yarn.yml
