---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_terminal: false
configure_osx: false

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

homebrew_installed_packages:
  - terraform
  - terragrunt
  - gnupg
  - bitwarden-cli
  - picocom
  - go
  - syncthing
  - jq
  - git
  - nmap
  - openssl
  - wget
  - curl
  - whois
  - bash-completion
  - neovim
  - tmux
  - neofetch
  - e2fsprogs
  - syncthing
  - bash
  - ripgrep
  - k9s
  - pinentry
  - openconnect
  - gocryptfs

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - vscodium
  - visual-studio-code
  - iterm2
  - alacritty
  - google-cloud-sdk
  - telegram
  - element
  - slack
  - vagrant
  - docker
  - eloston-chromium
  # maybe not this, will see
  - easy-move-plus-resize
  - spotify
  - signal
  - joplin

pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
