---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_terminal: false
configure_osx: false

configure_dock: false

mas_installed_apps:
  - { id: 1475387142, name: "Tailscale" }
  - { id: 1352778147, name: "Bitwarden" }
  - { id: 310633997, name: "WhatsApp Messenger" }

homebrew_installed_packages:
  - bash-completion
  - gh
  - glab
  - sops
  - hugo
  - helm
  - terraform
  - terragrunt
  - gnupg
  - bitwarden-cli
  - picocom
  - go
  - node
  - jq
  - git
  - nmap
  - openssl
  - wget
  - curl
  - whois
  - neovim
  - tmux
  - neofetch
  - e2fsprogs
  - tree
  - ripgrep
  - k9s
  - pinentry
  - openconnect
  - speedtest-cli
  - watch
  - telnet
  - fzf

homebrew_taps: []
  # - homebrew/core
  # - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - rectangle
  - obs
  - firefox
  - visual-studio-code
  - iterm2
  - alacritty
  - google-cloud-sdk
  - element
  - slack
  - docker
  - spotify
  - signal
  - joplin
  - chatbox

npm_packages: []

pip_packages: []

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
